language: "python"

python: 
  - "3.7"

env:
  - DJANGO=2.2

install:
  - pip install -r requirements.txt

script:
  - pytest tests/test.py
  - black --check .
  # - coverage run --source=my_package manage.py test
  
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key: $SECRETACCESSKEY
  region: "us-west-2"  
  app: "django-tutorial"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-west-2-502730698175"
  on:
    branch: master
  