language: "python"

python: 
  - "3.7"

env:
  - DJANGO=2.2

install:
  - pip install -r requirements.txt
  - pip install importlib-metadata
  - pip install black
  # - pip install flake8
  # - pip install coverage
  # - pip insatll coveralls

script:
  - python manage.py test
  - python -m black . --check .
  # - coverage run --source=ebdjango,polls manage.py test
  # - python -m coverage report -m
  
# after_script:
#   - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key: $SECRETACCESSKEY
  region: "us-west-2"  
  app: "django-tutorial"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-west-2-502730698175"
  on:
    all_branches: true

after_success:
  -eb deploy