language: "python"

python: 
- "3.7"
- "2.7"

env:
- DJANGO=1.10.1

install:
- pip install -r requirements.txt

script:
- python manage.py test

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "AKIAXKDIVVW7UWQJHTFJ"
  secret_access_key:
    secure: "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"
  region: "us-west-2"
  app: "django-tutorial"
  env: "django-env"
  bucket_name: "elasticbeanstalk - us-west-2 - 502730698175"